[project]
name = "remote"
version = "0.1.0"
description = "Ableton.spoon remote server"
readme = "README.md"
requires-python = "3.11.6"
dependencies = []

[tool.basedpyright]
typeCheckingMode = "standard"
extraPaths = [
    "/Users/ethan/dev/AbletonLive12_MIDIRemoteScripts"
]
